
    
    //this variables must stay out of the loop so they can keep their values
    let playerScore = 0;
    let cpuScore= 0;

    // The loops allow the code to run 5 times to get the best out of 5 games
for (let games = 0; games < 5; games++){

    //normalices the strings from the text generated by the code and the player to fit into the the function mathRPS
    let computerChoice = getComputerChoise().toLowerCase();
    console.log(computerChoice)
    
    let playerChoise = prompt("Choose: Rock,Paper or Scissors!").toLowerCase();
    console.log(playerChoise)
        
    //creates a random number from 1 to 3
    var numberGenerator = Math.random() *3;
     
    console.log (numberGenerator)

    
    //asigns one of the 3 random number to rock,paper or scissor to be used by the function matchRPS
 function getComputerChoise() {
if (numberGenerator < 3 && numberGenerator > 2){
    return("ROCK");
} else if (numberGenerator < 2 && numberGenerator > 1){
    return("PAPER");
} else {
    return("SCISSORS");
}

}
   

  //takes the generation from the getComputerchoice funcion and the playerChoise variable,compares them and returns a winner to 
function matchRPS(computerChoice,playerChoise){
    if (computerChoice == playerChoise){
       return(`You: ${playerChoise}  -  CPU: ${computerChoice} IT'S A TIE! `)
   
    } else if(computerChoice == "rock" && playerChoise == "paper" || computerChoice == "scissors" && playerChoise == "rock" || computerChoice == "paper" && playerChoise == "scissors") {
        playerScore++
        return(`You: ${playerChoise} - CPU: ${computerChoice} YOU WIN! `);
        
    } else if (computerChoice == "paper" && playerChoise == "rock" || computerChoice == "rock" && playerChoise == "scissors" || computerChoice == "scissor" &&  playerChoise == "paper"){
        cpuScore++
        return(`You: ${playerChoise} - CPU: ${computerChoice} CPU WINS! `)
        
         
    } else {return(`${playerChoise} is not a valid option :(` )}

}


// shows an alert with the winner from the mathRPS function
console.log(matchRPS(computerChoice,playerChoise));
console.log(`Player Score: ${playerScore} CPU Score: ${cpuScore}`)
}

// returns the winner of the game
function winnerMessage(){
    if (playerScore > cpuScore){
      return("YOU WIN!")
    }else if(cpuScore){
        return("YOU LOOSE")
    }else return("It's a tie")
}

alert(winnerMessage())



















